taskmanageProject/accounts/urls.py
# accounts/urls.py

from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    # 회원가입, 회원정보 수정, 로그인, 로그아웃
    path('', views.base, name='base'), 
    path('signup/', views.signup, name='signup'),
    path("user_update/<int:id>/", views.user_update, name="user_update"),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    # 마이페이지
    path('my_page/<int:id>/', views.my_page, name='my_page'),

    path('agree1/', views.agree1, name='agree1'), 
    path('agree2/', views.agree2, name='agree2'), 
    path('agree3/', views.agree3, name='agree3'), 

    path('joinclear/', views.joinclear, name='joinclear'), 
]

taskmanageProject/taskmanageProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('accounts.urls', namespace='accounts')),
    path('team/',include('teams.urls', namespace='teams')),

    # 비밀번호 재설정(메일 전송)
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='../../accounts/templates/registration/find_password.html',  # 커스터마이즈한 템플릿 경로 지정
        email_template_name='../../accounts/templates/registration/password_reset_email.html',  # 이메일 템플릿 경로 지정
        subject_template_name='../../accounts/templates/registration/password_reset_subject.txt'  # 이메일 제목 템플릿 경로 지정
    ), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='../../accounts/templates/registration/find_passwordOK.html' 
    ), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='../../accounts/templates/registration/modify_password.html' 
    ), name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='../../accounts/templates/registration/modify_OK.html' 
    ), name="password_reset_complete"),
]

# 이미지 루트
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskmanageProject/teams/urls.py
from django.urls import path, include
from . import views

app_name = "teams"

urlpatterns = [
    # 팀 생성
    path('team_create/', views.TeamCreateView.as_view(), name='team_create'),
    path('team_update/<int:id>/', views.team_update, name='team_update'),
    path('team_delete/<int:team_id>/', views.team_delete, name='team_delete'),
    path('', views.team_list, name='team_list'),
    path('team_detail/<int:id>/', views.team_detail, name='team_detail'),

    # 팀 좋아요
    path('<int:team_id>/likes/', views.likes, name='likes'),

    # 할 일
    path('task_create/<int:id>/', views.task_create, name='task_create'),
    path('task_update/<int:id>/', views.task_update, name='task_update'),
    path('task_delete/<int:id>/', views.task_delete, name='task_delete'),
]

taskmanageProject/accounts/forms.py
from django import forms
from accounts.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import PasswordChangeForm


# 커스텀 유저
class CustomUserForm(forms.ModelForm):
    profile = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'hidden-file-input'}))
    class Meta:
        model = User
        fields = ['profile', 'username', 'password', 'email', 'name', 'phone', 'birthdate']

        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'userid-input',
                'placeholder': '아이디를 6자 이상 입력해주세요.',
            }),
            'email': forms.TextInput(attrs={
                'class': 'email-input',
                'placeholder': '예) rlfhvm@gmail.com',
            }),
            'password': forms.TextInput(attrs={
                'class': 'password-input',
                'placeholder': '비밀번호를 8자 이상 입력해주세요.',
            }),
            'name': forms.TextInput(attrs={
                'class': 'name-input',
                'placeholder': '예) 기로프',
            }),
            'phone': forms.TextInput(attrs={
                'class': 'phone-input',
                'placeholder': '예) 01012345678',
            }),
            'birthdate': forms.TextInput(attrs={
                'class': 'birthdate-input',
                'placeholder': '예) 2000-01-01',
            }),
            'profile': forms.FileInput(attrs={
                'class': 'profile-input',
                'id': 'profile-input',
                'style': 'display:none;'
            }),
        }
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])  # 비밀번호 해싱하기
        if commit:
            user.save()
        return user

# 커스텀 유저 업데이트    
class CustomUserUpdateForm(forms.ModelForm):
    profile = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'hidden-file-input clearable-file-input'}))
    # profile = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'hidden-file-input'}))
    class Meta:
        model = User
        fields = ['profile', 'username', 'email', 'name', 'phone', 'birthdate']
    

#--------------------------------------------------------------------------------------------------------


# class CustomPasswordChangeForm(PasswordChangeForm):
#     new_password1 = forms.CharField(
#         label='New password',
#         widget=forms.PasswordInput(attrs={'class': 'form-control'}),
#         min_length=8,
#         help_text="Your password can’t be too similar to your other personal information.<br>Your password must contain at least 8 characters.<br>Your password can’t be a commonly used password.<br>Your password can’t be entirely numeric."
#     )
#     new_password2 = forms.CharField(
#         label='Confirm new password',
#         widget=forms.PasswordInput(attrs={'class': 'form-control'}),
#         min_length=8
#     )

#     def clean_new_password1(self):
#         password1 = self.cleaned_data.get('new_password1')
#         if len(password1) < 8:
#             raise ValidationError("Password must be at least 8 characters long.")
#         return password1
    

taskmanageProject/teams/forms.py
from django import forms
from .models import Team, Task
from accounts.models import User


# Team 모델폼
class TeamModelForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'title_input',
            'placeholder': 'Untitled',
            })
    )
    # name = forms.CharField(widget=forms.ClearableFileInput(attrs={'class': '.title_input'}))
    photo = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'hidden-file-input'}))
    def __init__(self, *args, **kwargs):
        current_user = kwargs.pop('current_user', None)
        super().__init__(*args, **kwargs)
        
        # 유저 제외하고 체크박스 생성
        if current_user:
            users = User.objects.filter(is_superuser=False).exclude(pk=current_user.pk).order_by('username')
        else:
            users = User.objects.filter(is_superuser=False).order_by('username')
        
        self.fields['members'].queryset = users

    class Meta:
        model = Team
        fields = ['name', 'description', 'members', 'photo']
        ordering = ['-created_at']
        widgets = {
            'members': forms.CheckboxSelectMultiple(),  # 여러 명 선택 가능한 체크박스 위젯
        }
       
class TeamUpdateModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        current_user = kwargs.pop('current_user', None)
        super().__init__(*args, **kwargs)
        
        # 유저 제외하고 체크박스 생성
        if current_user:
            users = User.objects.filter(is_superuser=False).exclude(pk=current_user.pk).order_by('username')
        else:
            users = User.objects.filter(is_superuser=False).order_by('username')
        
        self.fields['members'].queryset = users

    class Meta:
        model = Team
        fields = ['members']
        widgets = {
            'members': forms.CheckboxSelectMultiple(),  # 여러 명 선택 가능한 체크박스 위젯
        }


# Task 모델폼
class TasksModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        team = kwargs.pop('team', None)
        super(TasksModelForm, self).__init__(*args, **kwargs)
        if team:
            self.fields['manager'].queryset = team.members.all()

    # def clean(self):
    #     cleaned_data = super().clean()
    #     manager_ids = self.cleaned_data.get('manager')
    #     if manager_ids:
    #         cleaned_data['manager'] = User.objects.filter(pk__in=manager_ids)
    #     return cleaned_data
    
    def clean(self):
        cleaned_data = super().clean()
        manager_ids = cleaned_data.get('manager')
        if not manager_ids:
            self.add_error('manager', '담당자를 선택해주세요.')
        return cleaned_data

    class Meta:
        model = Task
        fields = ['title', 'manager', 'finished']
        widgets = {
            'manager': forms.CheckboxSelectMultiple()
        }

taskmanageProject/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import User
from .forms import CustomUserForm, CustomUserUpdateForm
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from teams.models import Team, Task
from django.views.decorators.csrf import csrf_exempt
import json

# 첫 화면
def base(request):
    return render(request, 'account_base.html')

def agree1(request):
    return render(request, 'agree1.html')

def agree2(request):
    return render(request, 'agree2.html')

def agree3(request):
    return render(request, 'agree3.html')

def joinclear(request):
    return render(request, 'joinclear.html')

def profile(request):
    if request.method == 'POST':
        form = CustomUserForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = CustomUserForm(instance=request.user)

    return render(request, 'users/profile.html', {'form': form})

# 회원가입
@csrf_exempt
def signup(request,  edit=False):
    if request.method == 'POST' or request.method == 'FILES':
        form = CustomUserForm(request.POST, request.FILES)
        if form.is_valid():
            if request.POST['password'] == request.POST['userPasswordre']:
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                name = form.cleaned_data['name']
                phone = form.cleaned_data['phone']
                email = form.cleaned_data['email']
                birthdate = form.cleaned_data['birthdate']

            # 1. 아이디 길이 검사
                if len(username) < 6 or len(username) > 25:
                    error_message = "아이디를 6자 이상 입력해주세요." 
                    return render(request, 'join.html', {'error_message': error_message, 'form': form, 'is_edit': edit})
                
            # 2. 비밀번호 길이 검사
                if len(password) < 8:
                    error_message = "비밀번호를 8자 이상 입력해주세요." 
                    return render(request, 'join.html', {'error_message': error_message, 'form': form, 'is_edit': edit})
                
            # 3. 이름 길이 검사
                if len(name) < 2 or len(name) > 15:
                    error_message = "이름을 2자 이상 입력해주세요." 
                    return render(request, 'join.html', {'error_message': error_message, 'form': form, 'is_edit': edit})
                
            # 4. 전화번호 중복 & 길이 검사
                if User.objects.filter(phone=phone).exists():
                    error_message = "이미 가입되어있는 전화번호입니다." 
                    return render(request, 'join.html', {'error_message': error_message, 'form': form, 'is_edit': edit})
                
                if len(phone) != 11:
                    error_message = "'-'를 제외한 전화번호를 입력해주세요." 
                    return render(request, 'join.html', {'error_message': error_message, 'form': form, 'is_edit': edit})
                
            # 5. 이메일 중복 검사
                if User.objects.filter(email=email).exists():
                    error_message = "이미 존재하는 이메일입니다." 
                    return render(request, 'join.html', {'error_message': error_message, 'form': form, 'is_edit': edit})
                
                # 회원가입 성공
                form.save()
                return redirect('accounts:joinclear') 
            
            # 6. 비밀번호 일치 안할 경우
            else: 
                error_message = "비밀번호가 일치하지 않습니다." 
                return render(request, 'join.html', {'error_message': error_message, 'form': form, 'is_edit': edit})
        # 7. 아이디가 이미 존재할 경우
        else:
            error_message = "이미 존재하는 아이디이거나 입력 형태가 올바르지 않습니다." 
            return render(request, 'join.html', {'error_message': error_message, 'form': form, 'is_edit': edit})
    else:
        form = CustomUserForm()

    return render(request, 'join.html', {'form': form, 'is_edit': edit})



# 회원정보 수정
def user_update(request, id, edit=True):
    user = get_object_or_404(User, pk=id)

    if request.method == 'POST' or request.method == 'FILES':
        form = CustomUserUpdateForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            username = form.cleaned_data['username']
            name = form.cleaned_data['name']
            phone = form.cleaned_data['phone']
            email = form.cleaned_data['email']
            birthdate = form.cleaned_data['birthdate']

        # 1. 아이디 길이 검사
            if len(username) < 6 or len(username) > 25:
                error_message = "아이디를 6자 이상 입력해주세요." 
                return render(request, 'userinfo_modify.html', {'error_message': error_message, 'form': form, 'is_edit': edit})
            
        # 2. 이름 길이 검사
            if len(name) < 2 or len(name) > 15:
                error_message = "이름을 2자 이상 입력해주세요." 
                return render(request, 'userinfo_modify.html', {'error_message': error_message, 'form': form, 'is_edit': edit})
            
         # 3. 전화번호 중복 & 길이 검사
            if User.objects.filter(phone=phone).exclude(pk=user.pk).exists():
                error_message = "이미 가입되어있는 전화번호입니다." 
                return render(request, 'userinfo_modify.html', {'error_message': error_message, 'form': form, 'is_edit': edit})
            
            if len(phone) != 11:
                error_message = "'-'를 제외한 전화번호를 입력해주세요." 
                return render(request, 'userinfo_modify.html', {'error_message': error_message, 'form': form, 'is_edit': edit})
            
        # 4. 이메일 중복 검사
            if User.objects.filter(email=email).exclude(pk=user.pk).exists():
                error_message = "이미 존재하는 이메일입니다." 
                return render(request, 'userinfo_modify.html', {'error_message': error_message, 'form': form, 'is_edit': edit})

            user.username = username
            user.name = name
            user.phone = phone
            user.email = email
            user.birthdate = birthdate

            # 회원 수정 성공
            form.save()
            return redirect('teams:team_list') 
        
        #  5. 아이디가 이미 존재할 경우
        else:
            error_message = "이미 존재하는 아이디입니다." 
            return render(request, 'userinfo_modify.html', {'error_message': error_message, 'form': form, 'is_edit': edit})
    else:
        form = CustomUserUpdateForm(instance=user)

    return render(request, 'userinfo_modify.html', {'form':form, 'id':id, 'is_edit': edit})



# 로그인
def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            print('로그인 성공')
            return redirect('teams:team_list')
        else: 
            # 에러 메시지 설정
            error_message = "아이디 또는 비밀번호가 잘못되었습니다." 
            return render(request, 'login.html', {'error_message': error_message})
    else:
        return render(request, 'login.html')
    

# 로그아웃
def logout(request):
    auth_logout(request)
    print('로그아웃 성공')
    return redirect('teams:team_list') 


def get_team_task_data3(team_id):
    team = get_object_or_404(Team, pk=team_id)
    task_data = []
    for member in team.members.all():
        completed_tasks = Task.objects.filter(manager=member, finished=True, team=team).count()
        task_data.append({'username': member.username, 'completed_tasks': completed_tasks})
    return task_data

# 마이페이지
def my_page(request, id):
    user = get_object_or_404(User, pk=id)
    teams = user.teams.all().order_by('-created_at')
    team_data = {team.id: get_team_task_data3(team.id) for team in teams}

    context = {
        'user': user,
        'teams': teams,
        'team_data': json.dumps(team_data),
    }

    return render(request, 'mypage.html', context)


'''-------------------------------------------------------------------------------------------------'''

    
# 메일 보내기(참고용)
from django.core.mail.message import EmailMessage

def send_email(request):
    subject = "message"
    to = ["hayoun1114@naver.com"]
    from_email = "taskmanager202407@naver.com"
    message = "메지시 테스트"
    EmailMessage(subject=subject, body=message, to=to, from_email=from_email).send()

taskmanageProject/accounts/templates/account_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>계정 첫 화면</title>
</head>
<body>
    <h1>계정 첫화면</h1>
     <!-- 회원가입 / 로그인 -->
     {% if user.is_authenticated %} <!--로그인시-->
        {{ user.username }}님, 안녕하세요!<br><br>
        
        <a href="{% url 'accounts:logout' %}">로그아웃</a><br>
        <a href="{% url 'accounts:user_update' user.id %}">회원 정보 수정</a><br>
        <a href="{% url 'accounts:my_page' user.id %}">마이페이지</a></div><br>
     {% else %}  <!--로그아웃시-->
        <a href="{% url 'accounts:signup' %}">회원가입</a><br>
        <a href="{% url 'accounts:login' %}">로그인</a><br>
        <a href="{% url 'password_reset' %}">비밀번호 찾기</a><br>
     {% endif %}
     <!--회원가입 / 로그인 끝-->

     <a href="{% url 'teams:team_list' %}">팀 리스트</a><br>
    <!--팀 생성-->
    {% if user.is_authenticated %}
        <a href="{% url 'teams:team_create' %}">팀 생성</a>
    {%else %}
        <h4>팀 생성은 로그인 후 사용해주세요</h4>
    {% endif %}
    <!--팀 생성 여기까지-->
</body>
</html>

taskmanageProject/accounts/templates/index.html
{% load static %}

<!-- 메인페이지 -->

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>

    <!-- css -->
    <!-- 기본 css  -->
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/sytle.css' %}">

    <!-- main 페이지 css -->
    <link rel="stylesheet" href="{% static 'assets/css/section/main.css' %}?after">
    <title>기로프</title>
</head>
<body>
    <div class="main_wrap container">
        <header id="header">
            <h1><a href="{% url 'teams:team_list' %}">기로프</a></h1>
            {% if not user.is_authenticated %}
                <a href="{% url 'accounts:login' %}">로그인</a>
            {% else %}
                <!-- <a href="{% url 'accounts:logout' %}">로그아웃</a> -->
                <div>
                    <!-- <button class="create" onclick="showPop()"> -->
                    {% if user.is_authenticated %}
                        <a href="{% url 'teams:team_create' %}">
                            <button class="create">
                                <img src="{% static 'assets/img/plus.svg' %}" alt="">
                            </button>
                        </a>
                    {% else %}
                    {% endif %}
                    <a href="{% url 'accounts:my_page' user.id %}">
                        <!-- 유저 프로필 -->
                        <div class="profile"><img src="{{ user.profile.url }}" alt=""
                            style="width: 47px; height: 47px; border-radius: 50%; object-fit: cover;">
                        </div>
                    </a>
                </div>
            {% endif %}
        </header>
        <main id="main">
            <!-- 유저가 핀 한 팀 리스트 -->
            {% for team in liked_teams %}
                    <a href="{% url 'teams:team_detail' team.id %}">
                    <div class="box">
                        <div class="top">
                            <div class="top_header">
                                <h2>{{team.name}}</h2>
                                <img class="pin_img" src="{% static 'assets/img/pin_bold.svg' %}" alt="">
                            </div>
                            <div class="profile_box">
                                {% if team.photo %}
                                    <img src="{{ team.photo.url }}" alt="profile" class="profile">
                                {% else %}
                                    <img src="{% static 'assets/img/team_img.png' %}" alt="profile" class="profile">
                                {% endif %}
                            </div>
                        </div>
                        <div class="middle">
                            <div class="graph">
                                <canvas id="doughnut-chart-{{ team.id }}" width="100" height="100"></canvas>
                            </div>
                        </div>
                        <div class="bottom">
                            <div class="day">{{ team.created_at|date:"y.m.d" }}</div>
                        </div>                    
                    </div>
                </a>
            {% endfor %}

            <!-- 유저가 핀 안 한 팀 리스트 -->
            {% for team in other_teams %}
                <a href="{% url 'teams:team_detail' team.id %}">
                    <div class="box">
                        <div class="top">
                            <div class="top_header">
                                <h2>{{team.name}}</h2>
                                <img class="none" src="{% static 'assets/img/pin_bold.svg' %}" alt="">
                            </div>
                            <div class="profile_box">
                                {% if team.photo %}
                                    <img src="{{ team.photo.url }}" alt="profile" class="profile">
                                {% else %}
                                    <img src="{% static 'assets/img/team_img.png' %}" alt="profile" class="profile">
                                {% endif %}
                            </div>
                        </div>
                        <div class="middle">
                            <div class="graph">
                              
                                <canvas id="doughnut-chart-{{ team.id }}" width="100" height="100"></canvas>
                            </div>
                        </div>
                        <div class="bottom">
                            <div class="day">{{ team.created_at|date:"y.m.d" }}</div>
                        </div>                    
                    </div>
                </a>
            {% endfor %}
        </main>

        <!-- JSON 데이터 전달 -->
        <script id="liked-team-data" type="application/json">{{ liked_team_data|safe }}</script>
        <script id="other-team-data" type="application/json">{{ other_team_data|safe }}</script>
        
    </div>

    <!-- script -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.0/gsap.min.js"></script>
    <script src="{% static 'js/chart.js' %}?after"></script>

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            fetch('./team_create')
                .then(response => response.text())
                .then(data => {
                    document.getElementById('index-create-container').innerHTML = data;
                    initializeMainJS();
                })
                .catch(error => console.error('Error loading index_create.html:', error));
        });
    </script>

    <script>
        function initializeMainJS() {
            const Popup = document.querySelector('.popup_wrap');
            const No = document.querySelector('.no');
            const addTeam = document.querySelector('.add_team');
            const First = document.querySelector('.first');
            const Second = document.querySelector('.second');

            function showPop() {
                console.log(Popup)
                Popup.classList.remove('none');
            }

            function noPop() {
                Popup.classList.add('none');
            }

            // gsap 기본 상태
            gsap.set(addTeam, { bottom: '-400px' });

            function addFriend() {
                addTeam.classList.remove('none');
                gsap.to('.add_team', { duration: 1, bottom: "0", ease: "power3.out" });
            }

            function teamName() {
                console.log(First.classList)
                First.classList.add('none');
                Second.classList.remove('none');
            }

            window.showPop = showPop;
            window.noPop = noPop;
            window.addFriend = addFriend;
            window.teamName = teamName;
        }
        document.addEventListener('DOMContentLoaded', function() {
            const pinImages = document.querySelectorAll('.pin_img');

            pinImages.forEach(function(img) {
                if (!img.classList.contains('none')) {
                    img.closest('.box').classList.add('bordered');
                }
            });
        });
    </script>

</body>

</html>

taskmanageProject/accounts/templates/joinclear.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- css -->
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/sytle.css' %}?after">
    
    <link rel="stylesheet" href="{% static 'assets/css/section/join.css' %}">
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <link rel="stylesheet" href="{% static 'assets/css/section/joinclear.css' %}">
  
    <title>기로프</title>
</head>
    <body>
        <div class="join_wrap container">
            <div class="header">
                <div class="top">
                    <h1>회원가입</h1>
                </div>
            </div>
            <div class="clear">
                <div class="text-box">
                    <h2>회원가입 완료</h2>
                    <div class="text">
                        <h4><span class="grf">기로프</span>와 함께<br>할 일을 효율적으로 관리하고 분배할<br>홍길동님을 응원합니다!</h4>
                    </div>
                </div>
            </div>
            <div class="lottie-container" id="lottie">
                <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script> 
                <dotlottie-player src="https://lottie.host/1709475d-5814-4e94-b051-b69e37da223a/nrPZlpcBd7.json" background="transparent" speed="1" style="width: 300px; height: 300px;" loop="false;" autoplay></dotlottie-player>
            </div>
            <div class="btn-container">
                <a href="{% url 'teams:team_list' %}" class="joinClear gohome">홈으로</a>
                <a href="{% url 'accounts:login' %}" class="joinClear gologin">로그인 하러 가기</a>
            </div>
    </body>
</html>

taskmanageProject/accounts/templates/mypage.html
{% load static %}

<!-- 마이 페이지  -->

<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- 기본 css  -->
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/sytle.css' %}">

    <!-- main 페이지 css -->
    <link rel="stylesheet" href="{% static 'assets/css/section/mypage.css' %}">


    <!-- 차트 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>


    <title>기로프-마이페이지</title>
</head>

<body>
    <div class="mypage_wrap container">
        <div class="header">
            <div class="top">
                <button class="backbtn">
                    <a href="{% url 'teams:team_list' %}">
                        <img src="{% static 'assets/img/back.svg' %}" alt="backbtn">
                    </a>
                </button>
                <h1>마이페이지</h1>
            </div>
            <p>
                안녕하세요, <em>{{ user.name }}({{ user.username }})</em>님! <br />
                기로프로 더욱 편하게 <br />
                팀원들과 할 일을 한 눈에 확인해보세요. <br />
            </p>
        </div>
        <div class="modify_btn">
            <a href="{% url 'accounts:user_update' user.id %}">
                <button class="userinfo" type="button">회원정보 수정</button>
            </a>
            <a href="{% url 'accounts:logout' %}">
                <button>로그아웃</button>
            </a>
        </div>
        <div class="mypage_list_wrap">
            <h3><em>{{ user.name }}({{ user.username }})</em>님의 팀 목록</h3>
            {% for team in teams %}
            <!-- 팀 상세페이지 이동 -->
            <a href="{% url 'teams:team_detail' team.id %}">
                <div class="mypage_list">
                    <div class="list">
                        <h4>{{ team.name }}</h4>
                        <div class="team_info">
                            <div class="team_img">
                                {% if team.photo %}
                                    <img src="{{ team.photo.url }}" alt="profile" class="profile">
                                {% else %}
                                    <img src="{% static 'assets/img/default_team.png' %}" alt="profile" class="profile">
                                {% endif %}
                                <!-- <img src=" {% static 'assets/img/profile.png' %}" alt=""> -->
                            </div>
                            <!-- <div class="member">
                                {% for member in team.members.all %}
                                    {{ member.username }}
                                {% endfor %}
                            </div> -->
                            <div class="graph">
                                <canvas id="doughnut-chart-{{ team.id }}" width="100" height="100"></canvas>
                            </div>
                            <div class="info">
                                <p class="day">{{ team.created_at|date:"y.m.d" }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
        <script id="team-data" type="application/json">{{ team_data|safe }}</script>
    </div>

    <script src="{% static 'js/chart_mypage.js' %}"></script>
</body>

</html>