taskmanageProject/accounts/urls.py
# accounts/urls.py

from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    # 회원가입, 회원정보 수정, 로그인, 로그아웃
    path('', views.base, name='base'), 
    path('signup/', views.signup, name='signup'),
    path("user_update/<int:id>/", views.user_update, name="user_update"),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    # 마이페이지
    path('my_page/<int:id>/', views.my_page, name='my_page'),

    path('agree1/', views.agree1, name='agree1'), 
    path('agree2/', views.agree2, name='agree2'), 
    path('agree3/', views.agree3, name='agree3'), 

    path('joinclear/', views.joinclear, name='joinclear'), 
]

taskmanageProject/taskmanageProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('accounts.urls', namespace='accounts')),
    path('team/',include('teams.urls', namespace='teams')),

    # 비밀번호 재설정(메일 전송)
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='../../accounts/templates/registration/find_password.html',  # 커스터마이즈한 템플릿 경로 지정
        email_template_name='../../accounts/templates/registration/password_reset_email.html',  # 이메일 템플릿 경로 지정
        subject_template_name='../../accounts/templates/registration/password_reset_subject.txt'  # 이메일 제목 템플릿 경로 지정
    ), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='../../accounts/templates/registration/find_passwordOK.html' 
    ), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='../../accounts/templates/registration/modify_password.html' 
    ), name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='../../accounts/templates/registration/modify_OK.html' 
    ), name="password_reset_complete"),
]

# 이미지 루트
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskmanageProject/teams/urls.py
from django.urls import path, include
from . import views

app_name = "teams"

urlpatterns = [
    # 팀 생성
    path('team_create/', views.TeamCreateView.as_view(), name='team_create'),
    path('team_update/<int:id>/', views.team_update, name='team_update'),
    path('team_delete/<int:team_id>/', views.team_delete, name='team_delete'),
    path('', views.team_list, name='team_list'),
    path('team_detail/<int:id>/', views.team_detail, name='team_detail'),

    # 팀 좋아요
    path('<int:team_id>/likes/', views.likes, name='likes'),

    # 할 일
    path('task_create/<int:id>/', views.task_create, name='task_create'),
    path('task_update/<int:id>/', views.task_update, name='task_update'),
    path('task_delete/<int:id>/', views.task_delete, name='task_delete'),
]

taskmanageProject/teams/models.py
from django.db import models
from accounts.models import User

class Team(models.Model):
    name = models.CharField(verbose_name="팀 이름", max_length=8)
    description = models.TextField(verbose_name="팀 설명", blank=True)
    members = models.ManyToManyField(User, related_name='teams', blank=True)
    created_at = models.DateTimeField(verbose_name="팀 생성일", auto_now_add=True)
    creater = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    photo = models.ImageField(verbose_name="팀이미지", blank=True, null=True, upload_to='team_photo', default='team_photo/default_photo.jpg')
    like_users = models.ManyToManyField(User, related_name='like_teams')

    def __str__(self):
        return self.name
    
    def like_count(self):
        return self.like_users.count()
    

class Task(models.Model):
    title = models.CharField(verbose_name="할일 제목", max_length=100)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True)
    manager = models.ManyToManyField(User, related_name='manager', default=True) #할일 담당자
    finished = models.BooleanField(default=False)
    
    def __str__(self):
        return self.title
    
    def summary(self):
        return self.description[10]

taskmanageProject/teams/forms.py
from django import forms
from .models import Team, Task
from accounts.models import User


# Team 모델폼
class TeamModelForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'title_input',
            'placeholder': 'Untitled',
            })
    )
    # name = forms.CharField(widget=forms.ClearableFileInput(attrs={'class': '.title_input'}))
    photo = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'hidden-file-input'}))
    def __init__(self, *args, **kwargs):
        current_user = kwargs.pop('current_user', None)
        super().__init__(*args, **kwargs)
        
        # 유저 제외하고 체크박스 생성
        if current_user:
            users = User.objects.filter(is_superuser=False).exclude(pk=current_user.pk).order_by('username')
        else:
            users = User.objects.filter(is_superuser=False).order_by('username')
        
        self.fields['members'].queryset = users

    class Meta:
        model = Team
        fields = ['name', 'description', 'members', 'photo']
        ordering = ['-created_at']
        widgets = {
            'members': forms.CheckboxSelectMultiple(),  # 여러 명 선택 가능한 체크박스 위젯
        }
       
class TeamUpdateModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        current_user = kwargs.pop('current_user', None)
        super().__init__(*args, **kwargs)
        
        # 유저 제외하고 체크박스 생성
        if current_user:
            users = User.objects.filter(is_superuser=False).exclude(pk=current_user.pk).order_by('username')
        else:
            users = User.objects.filter(is_superuser=False).order_by('username')
        
        self.fields['members'].queryset = users

    class Meta:
        model = Team
        fields = ['members']
        widgets = {
            'members': forms.CheckboxSelectMultiple(),  # 여러 명 선택 가능한 체크박스 위젯
        }


# Task 모델폼
class TasksModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        team = kwargs.pop('team', None)
        super(TasksModelForm, self).__init__(*args, **kwargs)
        if team:
            self.fields['manager'].queryset = team.members.all()

    # def clean(self):
    #     cleaned_data = super().clean()
    #     manager_ids = self.cleaned_data.get('manager')
    #     if manager_ids:
    #         cleaned_data['manager'] = User.objects.filter(pk__in=manager_ids)
    #     return cleaned_data
    
    def clean(self):
        cleaned_data = super().clean()
        manager_ids = cleaned_data.get('manager')
        if not manager_ids:
            self.add_error('manager', '담당자를 선택해주세요.')
        return cleaned_data

    class Meta:
        model = Task
        fields = ['title', 'manager', 'finished']
        widgets = {
            'manager': forms.CheckboxSelectMultiple()
        }

taskmanageProject/teams/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .models import Team, Task
from accounts.models import User
from django.shortcuts import get_object_or_404
from teams.forms import TeamModelForm, TasksModelForm, TeamUpdateModelForm
from django.core.paginator import Paginator
import json


''' 팀 '''

# 팀 생성하기
class TeamCreateView(View):
    # 모든 유저목록 가져와서 team_create.html로 렌더
    def get(self, request):
        form = TeamModelForm(current_user=request.user)
        users = User.objects.all().order_by('username')  # 모든 사용자를 가져옴
        return render(request, 'team_made.html', {'form': form, 'users': users})

    # 팀 생성한 후 team_list.html로 리다이렉트
    def post(self, request):
        if request.method == 'POST' or request.method == 'FILES':
            form = TeamModelForm(request.POST, request.FILES, current_user=request.user)
            if form.is_valid():
                # team = form.save()  # 폼 데이터를 DB에 저장하고 팀 객체 반환
                unfinished_team = form.save(commit=False)
                unfinished_team.creater = request.user
                unfinished_team.save()

                # 유저 맴버에 추가하기
                unfinished_team.members.add(request.user)

                member_ids = request.POST.getlist('members')  # 선택된 멤버들의 ID 리스트
                
                for member_id in member_ids:
                    user = User.objects.get(pk=member_id)
                    unfinished_team.members.add(user)
                
                return redirect('accounts:my_page',  id=request.user.id)
        else: 
            users = User.objects.all().order_by('username')
            form = TeamModelForm(current_user=request.user)  # 현재 로그인한 사용자 정보 전달
        return render(request, 'team_made.html', {'form': form, 'users': users})
       

# 팀 수정하기
def team_update(request, id):
    team = get_object_or_404(Team, pk=id)
    if request.method == 'POST' or request.method == 'FILES':
        form = TeamUpdateModelForm(request.POST, request.FILES, instance=team, current_user=request.user)
        if form.is_valid():
            unfinished_team = form.save(commit=False)
            unfinished_team.creater = request.user
            unfinished_team.save()

            # 유저 맴버에 추가하기
            unfinished_team.members.add(request.user)
            
            member_ids = request.POST.getlist('members')  # 선택된 멤버들의 ID 리스트
                
            for member_id in member_ids:
                user = User.objects.get(pk=member_id)
                unfinished_team.members.add(user)
            
            return redirect('teams:team_list')
    else:
        form = TeamModelForm(instance=team, current_user=request.user)
        return render(request, 'team_member.html', {'form':form, 'id':id, 'team':team})
    

# 팀 삭제하기
def team_delete(request, team_id):
    team = get_object_or_404(Team, pk=team_id)
    team.delete()
    return redirect('accounts:base') 


# 팀 할일 조회
'''
def get_team_task_data(team):
    task_data = []
    for member in team.members.all():
        completed_tasks = Task.objects.filter(manager=member, finished=True).count()
        task_data.append({'username': member.username, 'completed_tasks': completed_tasks})
    return task_data
'''
def get_team_task_data(team_id):
    team = get_object_or_404(Team, pk=team_id)
    task_data = []
    for member in team.members.all():
        completed_tasks = Task.objects.filter(manager=member, finished=True, team=team).count()
        task_data.append({'username': member.username, 'completed_tasks': completed_tasks})
    return task_data

def get_team_task_data2(team_id):
    team = get_object_or_404(Team, pk=team_id)
    task_data = []
    for member in team.members.all():
        completed_tasks = Task.objects.filter(manager=member, finished=True, team=team).count()
        task_data.append({'username': member.username, 'completed_tasks': completed_tasks})
    team_member_count = team.members.count()
    team_task_count = Task.objects.filter(team=team).count()
    team_completed_tasks = Task.objects.filter(finished=True, team=team).count()
    return {'task_data': task_data, 'team_member_count': team_member_count, 
            'team_task_count': team_task_count, 'team_completed_tasks': team_completed_tasks}

# 팀 전체 조회
def team_list(request):
    if request.user.is_authenticated:
        liked_teams = Team.objects.filter(like_users=request.user).order_by('-created_at')
        other_teams = Team.objects.exclude(like_users=request.user).order_by('-created_at')
    else:
        liked_teams = Team.objects.none().order_by('-created_at')
        other_teams = Team.objects.all().order_by('-created_at')

    liked_team_data = {team.id: get_team_task_data(team.id) for team in liked_teams}
    other_team_data = {team.id: get_team_task_data(team.id) for team in other_teams}
    print(liked_team_data)
    context = {
        'liked_teams': liked_teams,
        'other_teams': other_teams,
        'liked_team_data': json.dumps(liked_team_data),
        'other_team_data': json.dumps(other_team_data),
    }
    return render(request, 'index.html', context)

# 팀 상세 조회
def team_detail(request, id):
    team = get_object_or_404(Team, pk=id)
    tasks = team.task_set.all()
    paginator = Paginator(tasks, 5)
    pagnum = request.GET.get('page')
    tasks = paginator.get_page(pagnum)
    
    team_data = get_team_task_data2(id)
    task_data = team_data['task_data']
    team_member_count = team_data['team_member_count']
    team_task_count = team_data['team_task_count']
    team_completed_tasks = team_data['team_completed_tasks']
    teamdata_json = json.dumps(task_data)

    return render(request, 'team_detail.html', {
        'team': team,
        'tasks': tasks,
        'task_data': task_data,
        'team_member_count': team_member_count,
        'team_task_count': team_task_count,
        'team_completed_tasks': team_completed_tasks,
        'teamdata': teamdata_json
    })







# 팀 좋아요
def likes(request, team_id):
    if request.user.is_authenticated:
        team = get_object_or_404(Team, pk=team_id)

        if team.like_users.filter(pk=request.user.pk).exists():
            team.like_users.remove(request.user)
        else:
            team.like_users.add(request.user)
        return redirect('teams:team_detail',  id=team.id)
    return redirect('teams:team_detail',  id=team.id)



''' 할 일 '''

# 할 일 생성하기
def task_create(request, id):
    team = get_object_or_404(Team, pk=id)
    if request.method == 'POST':
        form = TasksModelForm(request.POST, team=team)
        manager_ids = request.POST.getlist('manager')
        if form.is_valid():
            task_create = form.save(commit=False)
            task_create.team = team
            task_create.save()
            for manager_id in manager_ids:
                user = User.objects.get(pk=manager_id)
                task_create.manager.add(user)
            task_create.save()
            return redirect('teams:team_detail', id=id)
    else:
        form = TasksModelForm(team=team)

    tasks = Task.objects.filter(team=team)
    return render(request, 'team_todo.html', {'form': form, 'team': team, 'tasks': tasks})

# 할 일 수정하기
def task_update(request, id):
    task_update = get_object_or_404(Task, pk=id)  # 기존 할 일 객체를 가져옴
    team = task_update.team

    if request.method == 'POST':
        form = TasksModelForm(request.POST, request.FILES, instance=task_update, team=team)
        if form.is_valid():
            task_update = form.save(commit=False)
            task_update.manager.clear()
            for manager in form.cleaned_data['manager']:
                task_update.manager.add(manager)
            task_update.save()
            return redirect('teams:team_detail', id=task_update.team.id)
    else:
        form = TasksModelForm(instance=task_update, team=team)

    return render(request, 'team_todo.html', {'form': form, 'team': team, 'task_update': task_update})





# 할 일 삭제하기
def task_delete(request, id):
    task = get_object_or_404(Task, pk=id)
    team_id = task.team.id  # 할일이 속한 팀의 id를 가져옴
    task.delete()
    return redirect('teams:team_detail', id=team_id)

taskmanageProject/teams/templates/member_search.html
{% load static %}

<!-- 현재 사용 안하는 html   -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>팀원 검색</title>
</head>
<body>
    <h2>{{ team.name }}에 맴버 추가</h2>
    <form method="post">
        {% csrf_token %}
        <label for="username">사용자 이름:</label>
        <input type="text" id="username" name="username">
        <button type="submit">검색</button>
    </form>
    {% if members %}
    <h3>검색 결과:</h3>
    <ul>
        {% for member in members %}
            <li>{{ member.username }} - <a href="{% url 'team:add_member_confirm' team.id member.id %}">추가</a></li>
        {% empty %}
            <li>매칭되는 맴버 없음</li>
        {% endfor %}
    </ul>
    {% endif %}
</body>
</html>

taskmanageProject/teams/templates/task_create.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>할일 생성</title>
</head>
<body>
    <h2>할일 생성</h2>
    <form method="POST">
        {% csrf_token %}
        <label for="{{ form.title.id_for_label }}">할일 제목:</label><br>
        {{ form.title }}<br><br>

        <label for="{{ form.manager.id_for_label }}">담당자:</label><br>
            {{ form.manager }}<br><br>
    
            <label for="{{ form.finished.id_for_label }}">완료 여부:</label><br>
            {{ form.finished }}<br><br>
    
            <button type="submit">저장</button>
        </form>
    
        {% if form.errors %}
            <p style="color: red;">{{ form.errors }}</p>
        {% endif %}
    </body>
    </html>
    

taskmanageProject/teams/templates/team_create.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>팀 생성</title>
</head>
<body>
    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {% if not form.name.value %}
        <h1>새 팀 생성 페이지</h1>
    {% else %}
        <h1>팀 수정 페이지</h1>
    {% endif %}

    <div>
        <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
        {{ form.name }}
    </div><br>
    <div>
        <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
        {{ form.description }}
    </div><br>
    <div>
        <label for="{{ form.members.id_for_label }}">{{ form.members.label }}</label>
        {{ form.members }}
    </div><br>
    <div>
        <label for="{{ form.photo.id_for_label }}">{{ form.photo.label }}</label>
        {{ form.photo }}
    </div><br>

    {% if not form.name.value %}
        <input type="submit" value="새 팀 생성하기">
    {% else %}
        <input type="submit" value="팀 수정하기">
    {% endif %}

    </form>
</body>
</html>

taskmanageProject/teams/templates/team_detail.html
{% load static %}

<!-- 팀 상세페이지  -->
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- 차트 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>

    <!-- 기본 css  -->
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/sytle.css' %}">


    <!-- main 페이지 css -->
    <link rel="stylesheet" href="{% static 'assets/css/section/team.css' %}">

    <title>기로프-팀</title>
</head>

<body>
    <div class="team_wrap container">
        <div class="header">
            <a href="{% url 'teams:team_list' %}"><img class="ximg" src="{% static 'assets/img/back.svg' %}"
                    alt="down_pop"></a>
            <h2>{{ team.name }}</h2>
            <!-- 로그인 했을 때 -->
            {% if user.is_authenticated %}
            <form action="{% url 'teams:likes' team.id %}" method='POST'>
                {% csrf_token %}
                {% if user in team.like_users.all %}
                <button class="pin"><img class="pinimg" src="{% static 'assets/img/pin_bold.svg' %}" alt="pin"></button>
                {% else %}
                <button class="pin"><img class="pinimg" src="{% static 'assets/img/pin.svg' %}" alt="pin"></button>
                {% endif %}
            </form>
            <!-- 로그인 안 했을 때 -->
            {%else %}
            <button class="pin">
                <img class="pinimg" src="{% static 'assets/img/pin_bold.svg' %}" alt="pin" style="opacity: 0;">
            </button>
            <!-- 팀 고정은 로그인 후 사용해주세요. -->
            {% endif %}

        </div>
        <div class="team_member">
            <div class="team_header">
                <h3>팀원</h3>
                {% if request.user in team.members.all %}
                <a href="{% url 'teams:team_update' team.id %}" class="modify"><img
                        src="{% static 'assets/img/arrow_right.svg' %}" alt="modify"></a>
                {% else %}
                {% endif %}
            </div>
            <div class="team_list">
                <!-- 팀원 목록 -->
                {% for member in team.members.all %}
                <div class="profile">
                    <div>
                        <img src="{{ member.profile.url }}" alt="profile"
                            style="width: 50px; height: 50px; border-radius: 50%; object-fit: cover;">
                        <p>{{ member.username }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="todo">
            <div class="todo_header">
                <h3>할 일</h3>
                {% if request.user in team.members.all %}
                <a href="{% url 'teams:task_create' team.id %}"><img class="arrow_right"
                        src="{% static 'assets/img/arrow_right.svg' %}" alt="down_pop"></a>
                <!-- <button class="modify" onclick="modifyTodo()"><img src="{% static 'assets/img/modify.svg' %}" alt="modify"></button> -->
                {% endif %}
            </div>
            <div class="todo_list" style="text-align: center;">
                {% for task in tasks %}
                <div>
                    <p>{{ task.title }}</p>
                    {% if request.user in team.members.all %}
                    <div class="box">
                        <a href="{% url 'teams:task_update' task.id %}"><button type="button"><img class="modify"
                                    src="{% static 'assets/img/modify.svg' %}" alt="modify"></button></a>
                        <a href="{% url 'teams:task_delete' task.id %}"><button type="button"><img class="delete"
                                    src="{% static 'assets/img/x_bold.svg' %}" alt="x_bold"></button></a>
                    </div>
                    {% endif %}
                </div>

                {% empty %}
                <div class="todo_no">
                    <div class="nothing">
                        <img src="{% static 'assets/img/no_todo.png' %}" alt="bin">
                        <p>아직 작성된 할 일이 없어요</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="graph">
            <canvas id="doughnut-chart-{{ team.id }}" width="100" height="100"></canvas>
            <p><em class="percent_p"></em>%</p>
        </div>
    </div>

    <!-- team_data JSON 데이터 전달 -->
    <script id="teamdata" type="application/json">{{ teamdata|safe }}</script>
    <script id="team" type="application/json">{{ team.id }}</script>
    <script id="team_member_count" type="application/json">{{ team_member_count }}</script>
    <script id="team_task_count" type="application/json">{{ team_task_count }}</script>
    <script id="team_completed_tasks" type="application/json">{{ team_completed_tasks }}</script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.0/gsap.min.js"></script>

    <script src="{% static 'js/team.js' %}"></script>
    <script src=" {% static 'js/detail_chart.js' %}?after"></script>
    <script>
        const Percent = document.querySelector('.percent_p');

        if({{ team_completed_tasks }}* 100 / {{ team_task_count }}){
            Percent.innerHTML = {{ team_completed_tasks }}* 100 / {{ team_task_count }}
        } else {
            Percent.innerHTML = 0
        }
    </script>
</body>

</html>

taskmanageProject/teams/templates/team_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>팀 리스트</title>
</head>
<body>
    <h1>팀 리스트</h1>
    
    <div>
        <h2><유저가 좋아요 한 팀들></h2>
        <ul>
            {% for team in liked_teams %}
                <li>
                    {% if team.photo %}
                        <img src="{{ team.photo.url }}" alt="Team Picture" style="width: 100px; height: 100px">
                    {% else %}
                        <img src="{% static '../media/team_photo/default_photo.jpg' %}" alt="Team Picture" style="width: 100px; height: 100px">
                    {% endif %}
                        
                    <br>
                    
                    <a href="{% url 'teams:team_detail' team.id %}">
                    <strong>팀 이름: {{ team.name }}</strong><br></a>
                    <p>팀 생성일: {{ team.created_at }}</p>
                    팀 생성자 : {{ team.creater }}<br>
                    팀 설명: {{ team.description }}<br><br>
                    <strong>멤버:</strong>
                    <ul>
                        {% for member in team.members.all %}
                            <li>{{ member.username }}</li>
                        {% endfor %}
                    </ul>
                </li><hr>
            {% endfor %}
        </ul>
    </div>

    <div>
        <h2><유저가 좋아요 안 한 팀들></h2>
        <ul>
            {% for team in other_teams %}
                <li>
                    {% if team.photo %}
                        <img src="{{ team.photo.url }}" alt="Team Picture" style="width: 100px; height: 100px">
                    {% else %}
                        <img src="{% static '../media/team_photo/default_photo.jpg' %}" alt="Team Picture" style="width: 100px; height: 100px">
                    {% endif %}
                        
                    <br>
                    
                    <a href="{% url 'teams:team_detail' team.id %}">
                    <strong>팀 이름: {{ team.name }}</strong><br></a>
                    <p>팀 생성일: {{ team.created_at }}</p>
                    팀 생성자 : {{ team.creater }}<br>
                    팀 설명: {{ team.description }}<br><br>
                    <strong>멤버:</strong>
                    <ul>
                        {% for member in team.members.all %}
                            <li>{{ member.username }}</li>
                        {% endfor %}
                    </ul>
                </li><hr>
            {% endfor %}
        </ul>
    </div>


    <br>
    <!-- 회원가입 / 로그인 -->
    {% if user.is_authenticated %} <!--로그인시-->
    <a href="{% url 'teams:team_create' %}">새 팀 생성</a><br>
    <a href="{% url 'accounts:user_update' user.id %}">회원 정보 수정</a><br>
    <a href="{% url 'accounts:my_page' user.id %}">마이페이지</a></div><br>
    {% endif %}
     <!--회원가입 / 로그인 끝-->
     
     <br>
     <a href="{% url 'accounts:base' %}">메인페이지</a><br>
</body>
</html>

taskmanageProject/teams/templates/team_made.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- css -->
    <!-- 기본 css  -->
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/sytle.css' %}">

    <!-- main 페이지 css --> 
    <link rel="stylesheet" href="{% static 'assets/css/section/team_made.css' %}?after">

    <title>기로프-팀만들기</title>
    <style>
        /* 파일 입력 필드 숨기기 */
        .hidden-file-input {
            display: none;
        }
        /* 프로필 버튼 스타일 */
        .profilebtn-wrapper {
            cursor: pointer;
            display: inline-block;
            padding: 8px 16px;
            background-color: white;
            color: black;
            border: none;
            border-radius: 4px;
            text-align: center;
        }
        /* 레이블 스타일 */
        .profilebtn-label {
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="team_made container">
        <div class="header">
            <div class="top">
                <button class="backbtn">
                    <a href="{% url 'teams:team_list' %}">
                        <img src="{% static 'assets/img/back.svg' %}" alt="backbtn">
                    </a>
                </button>
                {% if not form.name.value %}
                    <h1>팀 생성</h1>
                {% else %}
                    <h1>팀 수정</h1>
                {% endif %}
                
            </div>
        </div>
        <div class="main">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="team_title">
                    <label for="title">팀 이름</label>
                    {{ form.name }}
                    <!-- <input type="text" placeholder="Unititeld"> -->
                </div>
                <div class="profile">
                    <label for="team_img">팀 이미지</label>
                    <div class="profilebtn-wrapper">
                        <label for="id_photo" class="profilebtn-label">
                            사진 추가
                        </label>
                        <!-- Django 폼 필드 (파일 입력 필드를 숨김) -->
                        {{ form.photo }}
                    </div>
                </div>
                <div class="team_memeber">
                    <label for="member">팀원</label>
                    <div class="list_wrap">
                        <div class="list">
                            {{ form.members }}
                            <!-- <p>admin</p>
                            <button type="button"><img src="../../static/assets/img/profilebtn.svg" alt=""></button> -->
                        </div>
                        
                    </div>
                </div>
                {% if not form.name.value %}
                    <button type="submit" class="submit_btn">생성</button>
                {% else %}
                    <button type="submit" class="submit_btn">수정</button>
                {% endif %}
            </form>
        </div>
    </div>
    <script>
        const TeamName = document.querySelector('.title_input');
        const SubmitBtn = document.querySelector('.submit_btn');

        TeamName.addEventListener('input', () => {
            if(TeamName.value !== ''){
                SubmitBtn.classList.add('full');
            } else {
                SubmitBtn.classList.remove('full');
            }
        })
    </script>
    <script src="{% static 'js/userinfo_modify.js' %}"></script>

</body>
</html>